<?php

declare(strict_types=1);

namespace App\Tests\Support;

/**
 * Identifiers are generated by Doctrine, so a unit test that never touches the
 * database has to stand in for it.
 */
trait AssignsEntityIds
{
    protected function assignId(object $entity, int $id): void
    {
        new \ReflectionProperty($entity, 'id')->setValue($entity, $id);
    }

    /**
     * @template T of object
     *
     * @param T $entity
     *
     * @return T
     */
    protected function withId(object $entity, int $id): object
    {
        $this->assignId($entity, $id);

        return $entity;
    }
}
