<?php

declare(strict_types=1);

namespace App\Tests\Unit\Product;

use App\Category\Entity\Category;
use App\Notification\Enum\OperationAction;
use App\Notification\NotificationDispatcher;
use App\Product\Dto\ProductChangedNotification;
use App\Product\Entity\Product;
use App\Product\Event\ProductChangedEvent;
use App\Product\EventListener\ProductChangedNotificationListener;
use App\Tests\Unit\Notification\Double\RecordingChannel;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;

/**
 * Exercises the seam between the product module and the notification module
 * through a real dispatcher and a recording channel, rather than mocking our own
 * classes — so it also proves the notification a channel actually receives.
 */
#[CoversClass(ProductChangedNotificationListener::class)]
#[CoversClass(ProductChangedNotification::class)]
final class ProductChangedNotificationListenerTest extends TestCase
{
    public function testTurnsASavedProductIntoANotificationForTheChannels(): void
    {
        $recorder = new RecordingChannel();
        $listener = new ProductChangedNotificationListener(
            new NotificationDispatcher([$recorder], $this->createStub(LoggerInterface::class)),
        );

        $product = $this->product(7, 'Pralka Bosch', '1299.50', [[3, 'AGD'], [4, 'RTV']]);

        $listener(new ProductChangedEvent(ProductChangedNotification::fromProduct($product, OperationAction::Created)));

        $received = $recorder->last();
        self::assertInstanceOf(ProductChangedNotification::class, $received);
        self::assertSame(ProductChangedNotification::TYPE, $received->getType());
        self::assertSame(OperationAction::Created, $received->getAction());
        self::assertSame('Product', $received->getSubjectType());
        self::assertSame(7, $received->getSubjectId());
        self::assertSame('notification.product.changed.subject', $received->getSubjectKey());
        self::assertSame([
            'productId' => 7,
            'name' => 'Pralka Bosch',
            'price' => '1299.50',
            'action' => 'created',
            'categories' => [
                ['id' => 3, 'code' => 'AGD'],
                ['id' => 4, 'code' => 'RTV'],
            ],
        ], $received->getContext());
    }

    public function testCarriesTheUpdateActionThrough(): void
    {
        $recorder = new RecordingChannel();
        $listener = new ProductChangedNotificationListener(
            new NotificationDispatcher([$recorder], $this->createStub(LoggerInterface::class)),
        );

        $listener(new ProductChangedEvent(ProductChangedNotification::fromProduct(
            $this->product(9, 'Czajnik', '99.00', [[3, 'AGD']]),
            OperationAction::Updated,
        )));

        self::assertInstanceOf(ProductChangedNotification::class, $recorder->last());
        self::assertSame(OperationAction::Updated, $recorder->last()->getAction());
        self::assertSame('updated', $recorder->last()->getContext()['action']);
    }

    /**
     * The audit payload is stored as JSON, so it must survive a round trip.
     */
    public function testTheContextIsJsonSerialisable(): void
    {
        $notification = ProductChangedNotification::fromProduct(
            $this->product(1, 'Mikser', '49.99', [[2, 'AGD']]),
            OperationAction::Created,
        );

        $json = json_encode($notification->getContext(), \JSON_THROW_ON_ERROR);

        self::assertSame($notification->getContext(), json_decode($json, true, 512, \JSON_THROW_ON_ERROR));
    }

    public function testRefusesToNotifyAboutAnUnpersistedProduct(): void
    {
        $this->expectException(\LogicException::class);

        // Channels read the persisted id; announcing before flush would be a lie.
        ProductChangedNotification::fromProduct(new Product('Bez id', '1.00'), OperationAction::Created);
    }

    /**
     * @param list<array{0: int, 1: string}> $categories
     */
    private function product(int $id, string $name, string $price, array $categories): Product
    {
        $product = new Product($name, $price);
        $this->assignId($product, $id);

        foreach ($categories as [$categoryId, $code]) {
            $category = new Category($code);
            $this->assignId($category, $categoryId);
            $product->addCategory($category);
        }

        return $product;
    }

    /**
     * Ids are generated by Doctrine, so a unit test has to stand in for it.
     */
    private function assignId(object $entity, int $id): void
    {
        $property = new \ReflectionProperty($entity, 'id');
        $property->setValue($entity, $id);
    }
}
